AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Voting system CFN template
Resources:
  VotingSystemFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.rest.test.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: target/maven-archetype-quickstart-1.0-SNAPSHOT.jar
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 20
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  VotingSystemApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/votingsystem'
    Export:
      Name: VotingSystemApi
